language: java

script:
- mvn clean install
- mvn test
- mvn package

deploy: &heroku
        provider: heroku
        app: siget_equipo1
        api_key: 18562f60-1231-4327-8b42-88518f1e5dde
        
before_install:
  - chmod +x mvnw