language: java

script:
- mvn clean
- mvn install
- mvn package spring-boot:repackage
- mvn test
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar


deploy: &heroku
        provider: heroku
        app: siget_equipo1
        api_key: 18562f60-1231-4327-8b42-88518f1e5dde

server:
        port: $PORT
  
before_install:
  - chmod +x mvnw
